version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: heigel
      MYSQL_DATABASE: optaddb
      MYSQL_USER: optad
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    depends_on:
      - mysql
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/docker
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/docker
    depends_on:
      - php
      - mysql